version: "2.4"

services:

  server:
    build:
      context: .
      args:
        MOODLE_BRANCH: MOODLE_37_STABLE
    container_name: moodle_server
    ports:
      - "80:80"
    volumes:
      - moodledata:/var/www/html/moodledata
      - ./scripts:/scripts
    networks:
      - moodle-net
    depends_on: 
      - db
    environment:
      DB_TYPE: pgsql
      DB_HOST: db
      DB_USER: dev_user
      DB_PASS: dev_passwd
      DB_NAME: moodle
      MOODLE_ADMINUSER: admin
      MOODLE_ADMINPASS: q1w2e3r4
      MOODLE_ADMINMAIL: example@mail.com
      MOODLE_NAME: moodle_default_docker
      MOODLE_WWWROOT: http://localhost/moodle

  db:
    image: postgres:latest
    container_name: moodle_db
    ports:
      - 5432:5432
    networks:
      - moodle-net
    volumes:
      - moodle-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_passwd
      POSTGRES_DB: moodle

networks:
  moodle-net:

volumes:
  moodle-db:
  moodledata:
