version: "2.4"

services:

  moodle:
    build:
      context: .
      args:
        MOODLE_BRANCH: MOODLE_37_STABLE
    container_name: moodle_server
    ports:
      - "80:80"
    volumes:
      - moodle-data:/var/www/moodledata
    networks:
      - moodle-net
    environment:
      DB_DRIVER: pgsql
      DB_HOST: moodle_db
      DB_USER: moodle
      DB_PASS: example
      DB_NAME: moodle
      MOODLE_ADMINUSER: admin
      MOODLE_ADMINPASS: q1w2e3r4
      MOODLE_ADMINMAIL: example@mail.com
      MOODLE_NAME: MoodleDocker
      MOODLE_WWWROOT: http://localhost/moodle

  moodle_db:
    image: postgres:latest
    container_name: moodle_db
    ports:
      - 3306:3306
    networks:
      - moodle-net
    volumes:
      - moodle-db-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: example
      POSTGRES_DB: moodle

networks:
  moodle-net:

volumes:
  moodle-db-data:
  moodle-data:
