version: "2.4"

services:

  moodle:
    build:
      context: .
      args:
        MOODLE_BRANCH: MOODLE_37_STABLE
    container_name: moodle_server
    ports:
      - "80:80"
    volumes:
      - moodle_data:/var/www/moodledata
    networks:
      - moodle_net
    environment:
      # DB_DRIVER: mysqli
      DB_DRIVER: pgsql
      DB_HOST: moodle_db
      DB_USER: moodle
      DB_PASS: example
      DB_NAME: moodle
      DB_PORT: 5432
      MOODLE_ADMINUSER: admin
      MOODLE_ADMINPASS: q1w2e3r4
      MOODLE_ADMINMAIL: example@mail.com
      MOODLE_NAME: MoodleDocker
      MOODLE_WWWROOT: http://localhost/moodle
    # command: ["--skip-db"]

  moodle_db:
    # image: mysql:5.6.46
    image: postgres:latest
    container_name: moodle_db
    networks:
      - moodle_net
    volumes:
      # - ./my.cnf:/etc/mysql/my.cnf
      - moodle_db_data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: moodle
      POSTGRES_PASSWORD: example
      POSTGRES_DB: moodle

networks:
  moodle_net:

volumes:
  moodle_db_data:
    driver: local
  moodle_data:
    driver: local
