# Compose file to test the image (dev purposes only)
version: "3.7"

services:
  moodle:
    image: lucatercas/moodle:latest
    build:
      context: .
      args:
        MOODLE_VERSION: MOODLE_38_STABLE
    ports:
      - "80:80"
    volumes:
      - moodle-moodledata:/var/www/moodledata
    networks:
      - moodle-net
    depends_on: 
      - db
    environment:
      DB_DRIVER: "pgsql"
      DB_HOST: "db"
      DB_USER: "dev_user"
      DB_PASS: "dev_passwd"
      DB_NAME: "moodle"
      MOODLE_ADMINUSER: "admin_user"
      MOODLE_ADMINPASS: "admin_passwd"
      MOODLE_ADMINMAIL: "example@mail.com"
      MOODLE_NAME: "moodle_default_docker"

  db:
    image: postgres:13-alpine
    ports:
      - "5432:5432"
    networks:
      - moodle-net
    volumes:
      - moodle-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "dev_user"
      POSTGRES_PASSWORD: "dev_passwd"
      POSTGRES_DB: "moodle"

networks:
  moodle-net:

volumes:
  moodle-data:
  moodle-moodledata:
