# Compose file to test the image (dev purposes only)
version: "3.7"

services:
  moodle:
    image: moodle-test
    restart: always
    build:
      context: .
      args:
        MOODLE_VERSION: v3.7.6
    ports:
      - "80:80"
    volumes:
      - moodle-moodledata:/var/www/moodledata
      - ./scripts/check_db.php:/scripts/check_db.php
      - ./scripts/docker-entrypoint.sh:/usr/local/bin/docker-entrypoint.sh
    networks:
      - moodle-net
    depends_on: 
      - db
    environment:
      DB_DRIVER: "pgsql"
      DB_HOST: "db"
      DB_USER: "postgres"
      DB_PASSWORD: "dev_passwd"
      MOODLE_ADMIN_PASSWORD: "admin_passwd"

  db:
    image: postgres:13-alpine
    restart: always
    ports:
      - "5432:5432"
    networks:
      - moodle-net
    volumes:
      - moodle-data:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: "dev_passwd"
      POSTGRES_DB: "moodle"

networks:
  moodle-net:

volumes:
  moodle-data:
  moodle-moodledata:
