name: Docker Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Docker Login
        if: github.ref == 'refs/heads/master'
        run: echo ${{ secrets.DOCKER_USERNAME }} | docker login -u ${{ secrets.DOCKER_PASSWORD || --password-stdin
      - name: Build and Push Latest
        if: github.ref == 'refs/heads/master'
        run: make build-push-latest
      - name: Build and Push v3.7.6
        if: github.ref == 'refs/heads/master'
        run: make build-push-version VERSION=v3.7.6
