name: Docker Deploy

on:
  push:
    branchs:
      - master

jobs:
  v3-8-3_latest:
    env:
      MOODLE_VERSION: v3.8.3
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: DOCKER_BUILDKIT=1 docker build -t lucastercas/moodle:$MOODLE_VERSION --build-arg BUILD_DATE=$(date +%D) --build-arg BUILD_VERSION="1.0.0" --build-arg BUILD_NUMBER=$GITHUB_RUN_NUMBER --build-arg GIT_COMMIT=$GITHUB_SHA .
      - name: Push
        run: |
          docker tag lucastercas/moodle:$MOODLE_VERSION lucastercas/moodle:latest
          docker push lucastercas/moodle:$MOODLE_VERSION
          docker push lucastercas/moodle:latest

  v3-7-6:
    env:
      MOODLE_VERSION: v3.7.6
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Docker Login
        uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build
        run: DOCKER_BUILDKIT=1 docker build -t lucastercas/moodle:$MOODLE_VERSION --build-arg MOODLE_VERSION=$MOODLE_VERSION --build-arg BUILD_DATE=$(date +%D) --build-arg BUILD_VERSION="1.0.0" --build-arg BUILD_NUMBER=$GITHUB_RUN_NUMBER --build-arg GIT_COMMIT=$GITHUB_SHA .
      - name: Push
        run: docker push ${{ secrets.DOCKER_USERNAME }}/moodle:$MOODLE_VERSION
