name: Docker Deploy

on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Latest
        if: github.ref == 'refs/heads/master'
        run: make build-push-latest
      - name: Build and Push v3.7.6
        if: github.ref == 'refs/heads/master'
        run: make build-push-version VERSION=v3.7.6
