name: Docker Deploy

on:
  push:
    branchs:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: azure/docker-login@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build v3.8.3
        env:
          MOODLE_VERSION: v3.8.3
        run: docker build -t lucastercas/moodle:$MOODLE_VERSION --build-arg BUILD_DATE=$(date +%D) --build-arg BUILD_VERSION="1.0.0" --build-arg BUILD_NUMBER=$GITHUB_RUN_NUMBER --build-arg GIT_COMMIT=$GITHUB_SHA .

